travis:
  secure:
    BINSTAR_TOKEN: Lqsxpm8GFbm4yCPOUfA49KJAMaWPFacBAMhHFql/8vWQG7ouH5T9led7VFRMH1HTkMZQuGNN/h1ar9+yz0EFbwZVn2G604ukfm6u5by9wT9uKtk4qdWcRomoMOdTQtDpP0HEc9yoqV2Sbql6iR7CLsiYLSqmTIrMdH35vMveFBlx+6VkzrS80JAFjIAEUncGyQhLhNjJWQfZp4tfkY/Mo6sd6kGrc8HgD8Un2ELzsw8NV0nykTtjGRkrSDC4WgCCRmWhG/GsOULaQqcWj4V9h+bseXSDeW+idHilKwCJbUT5zcax49WOBTh7KPphFevOm9nENWoKb91OUkFCyxVN3HFmgHWq45UOnhko5XLaPA0vyGj5BTGsDvfahV/S6ViZjTyHMRhs+ub6yi2K1/r6MIaqNn9VYwH6RV51xzCjY6YJwizYoC+rVWzwu8REmlZYJjv90y3EtIOaWPq+/sLh0b+DljuHs9sBeNAv0HA1f3YEegsTOCDJd9ztpcx/EvxP66mLrbmGP56KxSROzaG+IHUhQe8okWkzdhaUwMakDNAvHRffd4paUQGrkq5PMigeRkmtI+I4jCDFjmjVdkbKpQ6s4hjZoJanN4sgTf9jtEtqaJbNa1Jh14/5EWnjoQ5YmyPH+SrdlP2bZSKxVRfy3/ZQ32pr5s6dDNOZe/1A4Kw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
